version: "3.2"

services:
  grobid.app:
    container_name: agr.grobid.server
    image: 100225593120.dkr.ecr.us-east-1.amazonaws.com/agr_grobid_env:latest
    logging:
      driver: gelf
      options:
        gelf-address: 'udp://logs.alliancegenome.org:12201'
    ports:
      - "8070:8070"
    networks:
      - grobid
    env_file:
      - .env

networks:
  # The presence of these objects is sufficient to define them
  grobid:
